services:
  web:
    command: sh /scripts_docker/prod/run_web.sh 
    environment:
    - ENVIRONMENT=production

    # COMANDO PARA LEVANTAR EN PRODUCCIÓN docker compose -f docker-compose.yml -f docker-compose.prod.yml up

# En el proyecto en settings.py añadir: environment_variable = os.environ.get('ENVIRONMENT', '')
# En settings.py se transforman debug y allowed_hosts

# if environment_variable == 'development':
#   DEBUG = True
#   ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# if environment_variable == 'production':
#   DEBUG = False
#   ALLOWED_HOSTS = ['prod.localhost']